### ISSUE TITLE
Fails to compile in after nushell 0.75

### ISSUE THREAD

**Issue by ryan-preble** [fdncred/nu_plugin_regex#1]
Source code fails to compile after updates to crate nu_protocol. Namely, PluginExample appears to no longer exist and PluginSignature has been replaced with Signature. Renaming nu_protocol::PluginSignature to nu_protocol::Signature as well as removing code that uses nu_protocol::PluginExample allows it to compile and work correctly. 

Note: I am running Win11 22H2, compiling rust code with visual studio build tools.

**Comment by fdncred** [comment]
Hey @ryan-preble, Thanks for the issue.

You have to be using 0.76.1 right now to use this because the plugin signatures have changed, as you noticed. But this is a good thing because now plugins can have examples, where previously they were not allowed.

I've just pushed some updates to work with 0.76.1 so, as long as you have nushell cloned and pointed to correctly in the cargo.toml, everything should compile. I just did this myself without issues.

**Comment by ryan-preble** [comment]
> Hey @ryan-preble, Thanks for the issue.
> 
> You have to be using 0.76.1 right now to use this because the plugin signatures have changed, as you noticed. But this is a good thing because now plugins can have examples, where previously they were not allowed.
> 
> I've just pushed some updates to work with 0.76.1 so, as long as you have nushell cloned and pointed to correctly in the cargo.toml, everything should compile. I just did this myself without issues.

Ah my bad, I did this yesterday before nu 0.76 got posted to github

**Comment by fdncred** [comment]
No worries. I'm just happy to know that someone finds this plugin useful. Closing for now.
